name = "Shital Salke"
rol = "Software Developer"
email = "shital.sallke@gmail.com"
phone = "+1 (857) 544 9256"
birthday = ""
location = "Atlanta, Georgia, USA"
avatar = "./config/assets/avatars/my-avatar.png"
username = "shitalsalke" # <-- github user name
googlemaps = ""
presentation = """
I am currently pursuing MS in Computer Science at Georgia Institute of Technology, specializing in Interactive Intelligence and Machine Learning.
With a strong background in technologies like Java, Python, AngularJS, and cloud platforms such as AWS and GCP, I am passionate about solving complex problems through efficient coding practices and scalable architectures.

My interests lie in full-stack development, machine learning, and creating innovative tools that drive impactful solutions in the tech space.
I enjoy working on challenging projects that push the boundaries of what technology can achieve, while continuously learning and adapting to new trends in software development, ML, and AI.
"""
